Proj1/Controllers/ErrorController.cs
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using NLog;
using Proj1.Models.Filter;

namespace Proj1.Controllers
{
    //[ServiceFilter(typeof(CustomExceptionFilter))]
    public class ErrorController : Controller
    {
        private readonly ILogger logger = LogManager.GetCurrentClassLogger();
        [Route("Error/{statusCode}")]
        public IActionResult ErrorPage(int statusCode)
        {
            var statuscoderesult = HttpContext.Features.Get<IStatusCodeReExecuteFeature>();
            switch (statusCode)
            {
                case 404:
                    ViewBag.ErrorMessage = "Sorry, The resource you request could not found";
                    ViewBag.Path = $"{statuscoderesult.OriginalPath.Trim('/')}/{statuscoderesult.OriginalQueryString}";
                    logger.Warn($"Sorry, The resource you request could not found \n " +
                        $"{statuscoderesult.OriginalPath.Trim('/')}/{statuscoderesult.OriginalQueryString}");
                    break;
            }
            return View();
        }
    }
}

Proj1/Controllers/OperationsController.cs
using BAL.Repository;
using BAL.Repository.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Proj1.Models.Filter;
using System;

namespace Proj1.Controllers
{
    //[ServiceFilter(typeof(CustomExceptionFilter))]
    public class OperationsController : Controller
    {
        private readonly IStudentRepo context;
        private readonly ILinq context1;

        public OperationsController(IStudentRepo context, ILinq context1)
        {
            this.context = context;
            this.context1 = context1;
        }
        [HttpGet]
        //[ResponseCache(CacheProfileName = "ListCache")]
        public IActionResult StudentListBySchool()
        {
            //var data = context.StudentBySchool(schoolid());
            #region comment
            //ViewData["SortOrder"] = SortOrder;
            //switch(SortBy)
            //{
            //    case "Name":
            //        {
            //            switch (SortOrder)
            //            {
            //                case "Asc":
            //                    {
            //                        data = data.OrderBy(it => it.StudentName).ToList();
            //                        break;
            //                    }
            //                case "Desc":
            //                    {
            //                        data = data.OrderByDescending(it => it.StudentName).ToList();
            //                        break;
            //                    }
            //                default:
            //                    {
            //                        data = data.OrderBy(it => it.StudentName).ToList();
            //                        break;
            //                    }
            //            }
            //            break;
            //        }
            //    case "RollNo":
            //        {
            //            switch (SortOrder)
            //            {
            //                case "Asc":
            //                    {
            //                        data = data.OrderBy(it => it.StudentRollNo).ToList();
            //                        break;
            //                    }
            //                case "Desc":
            //                    {
            //                        data = data.OrderByDescending(it => it.StudentRollNo).ToList();
            //                        break;
            //                    }
            //                default:
            //                    {
            //                        data = data.OrderBy(it => it.StudentRollNo).ToList();
            //                        break;
            //                    }
            //            }
            //            break;
            //        }
            //    default:
            //        {
            //            break;
            //        }
            //}
            #endregion
            return View();
        }
        [HttpGet]
        public JsonResult getstudentListBySchool()
        {
            return Json(context.StudentBySchool(schoolid()));
        }
        [HttpGet]
        public IActionResult SchoolClass(string a)
        {
            if (a != null)
            {
                HttpContext.Session.SetString("pageValue", a);
            }
            else
            {
                HttpContext.Session.SetString("pageValue", "");
            }
            return View();
        }
        [HttpGet]
        public IActionResult StudentListByClassId(int id)
        {
            return View();
        }
        [HttpGet]
        public JsonResult getStudentListByClassId(string id)
        {
            return Json(context.StudentByClassId(schoolid(), Convert.ToInt32(id)));
        }
        [HttpGet]
        public JsonResult getClass()
        {
            return Json(context.Classes());
        }
        [HttpGet]
        //[ResponseCache(CacheProfileName = "ListCache")]
        public IActionResult ShowAllResult()
        {
            return View(/*context.ResultBySchool(schoolid())*/);
        }
        [HttpGet]
        public JsonResult getShowAllResult()
        {
            return Json(context.ResultBySchool(schoolid()));
        }
        public IActionResult StudentResultByClassId(int id)
        {
            return View(/*context1.resultByClassId(schoolid(), id)*/);
        }
        [HttpGet]
        public JsonResult getStudentResultByClassId(int id)
        {
            return Json(context.resultByClassId(schoolid(), id));
        }
        [HttpGet]
        public IActionResult StudentById(int sid)
        {
            return View(context.StudentById(sid));
        }
        private int schoolid()
        {
            return Convert.ToInt32(HttpContext.Session.GetString("schoolId"));
        }
    }
}

Proj1/Controllers/SchoolController.cs
using BAL.Repository.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Proj1.Models.Filter;
using System;

namespace Proj1.Controllers
{
    //[ServiceFilter(typeof(CustomExceptionFilter))]
    public class SchoolController : Controller
    {
        private readonly IStudentRepo context;

        public SchoolController(IStudentRepo context)
        {
            this.context = context;
        }
        public IActionResult Index()
        {
            HttpContext.Session.SetString("schoolId", string.Empty);
            return View();
        }
        [HttpGet]
        public IActionResult ShowSchool(int id)
        {
            var data = context.School(id == 0 ? Convert.ToInt32(HttpContext.Session.GetString("schoolId")) : id);
            HttpContext.Session.SetString("schoolId", data.SchoolId.ToString());
            return View(data);
        }
        [HttpGet]
        public JsonResult getSchool()
        {
            return Json(context.Schools());
        }
    }
}

Proj1/Controllers/StudentController.cs
using Aspose.Words;
using Aspose.Words.Reporting;
using Aspose.Words.Tables;
using BAL.Repository;
using BAL.Repository.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Models.Models;
using Models.VM;
using Proj1.Models.Filter;
using System;
using System.Collections.Generic;
using System.Drawing;

namespace Proj1.Controllers
{
    [CustomAuthenticationFilter]
    [Authorize(Roles = "Admin,Teacher")]
    //[ServiceFilter(typeof(CustomExceptionFilter))]
    public class StudentController : Controller
    {
        private readonly IStudentRepo context;
        private readonly ILinq context1;

        public StudentController(IStudentRepo context, ILinq context1)
        {
            this.context = context;
            this.context1 = context1;
        }
        private int schoolid()
        {
            return Convert.ToInt32(HttpContext.Session.GetString("schoolId"));
        }
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult PostStudent()
        {
            var clist = context.Classes();
            clist.Insert(0, new Classes { ClassId = 0, ClassName = "---select---" });
            ViewBag.classes = clist;
            ViewBag.pageid = 0;
            return View();
        }
        [HttpPost]
        public IActionResult PostStudent(StudentVM stu)
        {
            stu.SchoolId = schoolid();
            if(stu.StudentId == 0)
            {
                if (context.InsertStudent(stu))
                {
                    return RedirectToAction("Index");
                }
            }
            else
            {
                if(context.UpdateStudent(stu))
                {
                    return RedirectToAction("Index");
                }
            }
            return View();
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            if(id !=0)
            {
                var clist = context.Classes();
                //var culist = context.GetCountry();
                //var slist = context.GetState(st.Cid);
                //var cityl = context.GetCity(st.Sid);
                //clist.Insert(0, new Classes { ClassId = 0, ClassName = "---select---" });
                //culist.Insert(0, new Country { Cid = 0, CName = "---select---" });
                //slist.Insert(0, new State { Sid = 0, SName = "---select---" });
                //cityl.Insert(0, new City { CityId = 0, CityName = "---select---" });
                ViewBag.classes = clist;
                return View();
            }
            return View();
        }
        [HttpGet]
        public JsonResult GetCountry()
        {
            return Json(context.GetCountry());
        }
        [HttpGet]
        public JsonResult GetState(int sid)
        {
            return Json(context.GetState(sid));
        }
        [HttpGet]
        public JsonResult GetCity(int Stateid)
        {
            return Json(context.GetCity(Stateid));
        }
        [HttpGet]
        public IActionResult ShowStudentById(int id)
        {
            var data = context.StudentById(id);
            if(data != null)
            {
                return PartialView("_ShowStudent", data);
            }
            return Ok("nullData");
        }
        [HttpGet]
        public JsonResult GetStudent(string stid)
        {
            return Json(context.EditStudentById(Convert.ToInt32(stid)));
        }
        [HttpGet]
        public JsonResult getStudents()
        {
            var data = context.StudentBySchool(schoolid());
            return Json(data);
        }
        [HttpPost]
        public JsonResult DeleteStudent(int id)
        {
            if(context.DeleteStu(id))
            {
                return Json("Student Remove success");
            }
            return Json("something went wrong");
        }
        [HttpGet]
        public JsonResult HtmlToPDF()
        {
            var data = context.StudentBySchool(schoolid());
            #region without template
            //Document doc = new();
            //DocumentBuilder docbuild = new(doc);
            //Table tbl = docbuild.StartTable();
            ////docbuild.InsertCell();
            ////docbuild.Write("Student Data Table");
            ////one cell ka formate set krna k liya
            ////tbl.PreferredWidth = PreferredWidth.FromPercent(150);
            ////docbuild.CellFormat.PreferredWidth = PreferredWidth.FromPercent(50);
            ////docbuild.CellFormat.Borders.LineWidth = 1.5;
            ////docbuild.CellFormat.Shading.BackgroundPatternColor = Color.Pink;
            ////docbuild.ParagraphFormat.Alignment = ParagraphAlignment.Center;
            ////docbuild.EndRow();
            ////Header Design
            //docbuild.InsertCell();
            //docbuild.Write("Student Id");
            //tbl.PreferredWidth = PreferredWidth.FromPercent(150);
            //docbuild.CellFormat.PreferredWidth = PreferredWidth.FromPercent(10);
            //docbuild.CellFormat.Borders.LineWidth = 1.5;
            //docbuild.CellFormat.Shading.BackgroundPatternColor = Color.Pink;
            //docbuild.ParagraphFormat.Alignment = ParagraphAlignment.Center;

            //docbuild.InsertCell();
            //docbuild.Write("Student Name");
            //docbuild.CellFormat.PreferredWidth = PreferredWidth.FromPercent(10);

            //docbuild.InsertCell();
            //docbuild.Write("Roll No");
            //docbuild.CellFormat.PreferredWidth = PreferredWidth.FromPercent(10);

            //docbuild.InsertCell();
            //docbuild.Write("Class");
            //docbuild.CellFormat.PreferredWidth = PreferredWidth.FromPercent(10);

            //docbuild.InsertCell();
            //docbuild.Write("Address");
            //docbuild.CellFormat.PreferredWidth = PreferredWidth.FromPercent(10);

            //docbuild.EndRow();
            ////Header Insert in Doc
            //foreach(Cell cell in tbl.Rows[0].Cells)
            //{
            //    Paragraph p = cell.FirstParagraph;
            //    p.Runs[0].Font.Bold = true;
            //    p.Runs[0].Font.Color = Color.White;
            //}
            ////this proces to insert tbody
            //Cell currentcell;
            //foreach (var item in data)
            //{
            //    currentcell = docbuild.InsertCell();
            //    docbuild.Write(item.StudentId.ToString());
            //    docbuild.ParagraphFormat.Alignment = ParagraphAlignment.Left;
            //    currentcell.CellFormat.VerticalMerge = CellMerge.First;
            //    docbuild.CellFormat.Borders.LineWidth = 1;
            //    docbuild.CellFormat.Shading.BackgroundPatternColor = Color.White;

            //    currentcell = docbuild.InsertCell();
            //    docbuild.Write(item.StudentName);

            //    currentcell = docbuild.InsertCell();
            //    docbuild.Write(item.StudentRollNo.ToString());

            //    currentcell = docbuild.InsertCell();
            //    docbuild.Write(item.ClassName);

            //    currentcell = docbuild.InsertCell();
            //    docbuild.Write(item.StudentAddress);

            //    docbuild.EndRow();

            //}
            ////file save path
            //doc.Save($"C:\\Users\\gauravverma\\Downloads\\reports.doc");
            #endregion
            #region with Template
            Document doc = new(@"C:\Users\gauravverma\Desktop\My_School_Proj\Proj1\Models\Template\StudentTemplate.docx");
            List<StudentVM> students = new(data);
            ReportingEngine reporting = new();
            reporting.BuildReport(doc, students, "student");
            doc.Save(@"C:\Users\gauravverma\Desktop\My_School_Proj\Proj1\wwwroot\TXT\OutPut\\Reports.docx");
            #endregion
            return Json("Export");
        }
    }
}

Proj1/Views/Shared/_Error.cshtml
@{
    ViewData["Title"] = "Error";
    ViewData["pageTitle"] = "Error Page";
    string ex = ViewData["HandleException"] as string;
    string InnerException = ViewData["InnerException"] as string;
}

<h1 class="text-danger">@ex</h1>

<div class="text-danger">@InnerException</div>

<a class="btn btn-outline-danger" asp-controller="School" asp-action="Index">Back To School List</a>

Proj1/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.0/css/jquery.dataTables.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (Context.Session.GetString("userLoginName") != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="School" asp-action="Index">School Project</a>
                            </li>
                        }
                    </ul>
                    <ul class="navbar-nav">
                        @if (Context.Session.GetString("userLoginName") != null)
                        {
                            <li class="nav-item"><a class="nav-link">Hi @Context.Session.GetString("userLoginName").ToString()</a></li>
                            <li class="nav-item"><a class="nav-link" asp-controller="User" asp-action="Logout"> LogOut </a></li>
                        }
                        @*else
                            {
                                <li class="nav-item"><a class="nav-link">Hi @Context.Session.GetString("userLoginName").ToString()</a></li>
                                <li class="nav-item"><a class="nav-link" asp-controller="User" asp-action="Logout"> LogOut </a></li>
                            }*@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="jumbotron">
        <h1 class="display-3 text-center">@ViewData["pageTitle"]</h1>
        <hr class="my-2">
    </div>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle"></h5>
                    <a class="btn btn-danger" asp-controller="Student" asp-action="Index" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </a>
                </div>
                <div class="modal-body">
                    
                </div>
                <div class="modal-footer">
                    <a class="btn btn-danger" asp-controller="Student" asp-action="Index">Close</a>
                </div>
            </div>
        </div>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Created By Gaurav Verma
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.0/js/jquery.dataTables.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Proj1/Views/Shared/_ShowStudent.cshtml
@model StudentVM
@{ 
    ViewData["Title"] = "Show";
    ViewData["pageTitle"] = "Student";
    Layout = null;
}

<div class="card col-md-12" style="width: 29rem;">
    <div class="card-body">
        <div class="row">
            <div class="col-md-6">
                <h5 class="card-title">Student Id:</h5>
            </div>
            <div class="col-md-6">
                <h5 class="card-title">@Model.StudentId</h5>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <h5 class="card-title">Student Name:</h5>
            </div>
            <div class="col-md-6">
                <h5 class="card-title">@Model.StudentName</h5>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <h5 class="card-title">Class:</h5>
            </div>
            <div class="col-md-6">
                <h5 class="card-title">@Model.ClassName</h5>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <h5 class="card-title">Roll Number:</h5>
            </div>
            <div class="col-md-6">
                <h5 class="card-title">@Model.StudentRollNo</h5>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <h5 class="card-title">Address:</h5>
            </div>
            <div class="col-md-6">
                <h5 class="card-title">@Model.StudentAddress</h5>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <h5 class="card-title">Result in % :</h5>
            </div>
            <div class="col-md-6">
                <h5 class="card-title">@Model.Percentage</h5>
            </div>
        </div>
    </div>
</div>

Proj1/Views/Shared/_StudentForm.cshtml
@model StudentVM

<form asp-controller="Student" asp-action="PostStudent" method="post">
    <input type="hidden" asp-for="StudentId" id="StudentId" />
    <div class="form-group row p-2">
        <label class=" col-md-2 text-center col-form-label">Student Name</label>
        <div class="col-md-5">
            <input class=" form-control" id="StudentName" onchange="changeCss('StudentName')"
                   type="text" asp-for="StudentName" placeholder="Student Name" />
        </div>
    </div>
    <div class="form-group row p-2">
        <label class="col-md-2 text-center form-label">Roll Number</label>
        <div class="col-md-5">
            <input class=" form-control" type="number" onchange="changeCss('StudentRollNo')"
                   asp-for="StudentRollNo" id="StudentRollNo" placeholder="Roll Number" />
        </div>
    </div>
    <div class="form-group row p-2">
        <label class="col-md-2 text-center form-label">Class</label>
        <div class="col-md-5">
            <select asp-for="ClassId" class="form-control" onchange="changeCss('ClassId')"
                    asp-items="@(new SelectList(ViewBag.classes,"ClassId","ClassName"))">
            </select>
        </div>
    </div>
    <div class="form-group row p-2">
        <label class="col-md-2 text-center form-label">Country</label>
        <div class="col-md-5">
            <select asp-for="Cid" id="cid" class="form-control" onchange="BindState(), changeCss('cid')">
            </select>
        </div>
    </div>
    <div class="form-group row p-2">
        <label class="col-md-2 text-center form-label">State</label>
        <div class="col-md-5">
            <select asp-for="Sid" id="sid" class="form-control" onchange="BindCity(), changeCss('sid')">
            </select>
        </div>
    </div>
    <div class="form-group row p-2">
        <label class="col-md-2 text-center form-label">City</label>
        <div class="col-md-5">
            <select asp-for="CityId" id="cityid" class="form-control" onchange="changeCss('cityid')" >
            </select>
        </div>
    </div>
    <div class="form-group row p-2">
        <label class="col-md-2 text-center form-label">Address</label>
        <div class="col-md-5">
            <input class=" form-control" type="text" onchange="changeCss('StudentAddress')"
                   asp-for="StudentAddress" id="StudentAddress" placeholder="Address" />
        </div>
    </div>
    <div class="form-group row">
        <div class="text-md-end p-1 col-md-5 m-1">
            @if (ViewBag.pageid == 0)
            {
                <button type="submit" class="btn btn-outline-success" onclick="return Validation()">Submit</button>
            }
            else
            {
                <button type="submit" class="btn btn-outline-secondary" onclick="return Validation()">Update</button>
            }
        </div>
    </div>
</form>

Proj1/Views/Shared/_StudentList.cshtml
@model List<StudentVM>


@foreach (var d in Model)
{
    @if (d.SchoolName == null && d.Percentage == 0)
    {
        <tr>
            <td>
                @d.StudentId
            </td>
            <td>
                @d.StudentName
            </td>
            <td>
                @d.StudentRollNo
            </td>
            <td>
                @d.StudentAddress
            </td>
            <td>
                <a class="btn btn-outline-info" asp-action="StudentById" asp-controller="Operations"
                   asp-route-sid="@d.StudentId">
                    View
                </a>
            </td>
        </tr>
    }
    else
   if (d.SchoolName != null && d.Percentage == 0)
    {
        <tr>
            <td>
                @d.StudentId
            </td>
            <td>
                @d.StudentName
            </td>
            <td>
                @d.StudentRollNo
            </td>
            <td>
                @d.ClassName
            </td>
            <td>
                @d.SchoolName
            </td>
            <td>
                @d.StudentAddress
            </td>
        </tr>
    }
    else
   if (d.Percentage != 0 && d.ClassName != null)
    {
        <tr>
            <td>
                @d.StudentId
            </td>
            <td>
                @d.StudentName
            </td>
            <td>
                @d.StudentRollNo
            </td>
            <td>
                @d.ClassName
            </td>
            <td>
                @d.StudentAddress
            </td>
            <td>
                @d.Percentage
            </td>
            <td>
                <a class="btn btn-outline-info" asp-action="StudentById" asp-controller="Operations" asp-route-sid="@d.StudentId">
                    View
                </a>
            </td>
        </tr>
    }
    else
       if (d.Percentage != 0 && d.ClassName == null)
    {
        <tr>
            <td>
                @d.StudentId
            </td>
            <td>
                @d.StudentName
            </td>
            <td>
                @d.StudentRollNo
            </td>
            <td>
                @d.StudentAddress
            </td>
            <td>
                @d.Percentage
            </td>
            <td>
                <a class="btn btn-outline-info" asp-action="StudentById" asp-controller="Operations" asp-route-sid="@d.StudentId">
                    View
                </a>
            </td>
        </tr>
    }
}